//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSY.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class msyEntities : DbContext
    {
        public msyEntities()
            : base("name=msyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<tbl_demand> tbl_demand { get; set; }
        public virtual DbSet<tbl_districts> tbl_districts { get; set; }
        public virtual DbSet<Tbl_JobCard> Tbl_JobCard { get; set; }
        public virtual DbSet<tbl_jobcard_jobcardmember> tbl_jobcard_jobcardmember { get; set; }
        public virtual DbSet<tbl_jobcardmembers> tbl_jobcardmembers { get; set; }
        public virtual DbSet<tbl_ulb_targets> tbl_ulb_targets { get; set; }
        public virtual DbSet<tbl_ulbs> tbl_ulbs { get; set; }
        public virtual DbSet<tbl_wards> tbl_wards { get; set; }
    }
}
