//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_jobcardmembers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_jobcardmembers()
        {
            this.tbl_jobcard_jobcardmember = new HashSet<tbl_jobcard_jobcardmember>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string dob { get; set; }
        public string gender { get; set; }
        public string aadhaar { get; set; }
        public Nullable<int> mobileNumber { get; set; }
        public string isHeadOfFamily { get; set; }
        public string relation { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_jobcard_jobcardmember> tbl_jobcard_jobcardmember { get; set; }
    }
}
