//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_demand
    {
        public int id { get; set; }
        public int jobcard_no { get; set; }
        public int demand_no { get; set; }
        public string status { get; set; }
        public string adhar_no { get; set; }
        public int demand_day { get; set; }
        public string submissionUserID { get; set; }
        public string submissionType { get; set; }
        public string demand_district { get; set; }
        public string demand_ulb { get; set; }
        public Nullable<int> demand_ward { get; set; }
        public string type { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    }
}
