//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_JobCard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_JobCard()
        {
            this.tbl_jobcard_jobcardmember = new HashSet<tbl_jobcard_jobcardmember>();
        }
    
        public int id { get; set; }
        public string address { get; set; }
        public Nullable<int> pincode { get; set; }
        public Nullable<int> ward { get; set; }
        public Nullable<int> ulb { get; set; }
        public Nullable<int> district { get; set; }
        public string urbanResidenceDeclaration { get; set; }
        public string consent { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> insertTime { get; set; }
        public string applicationRefrenceNumber { get; set; }
        public Nullable<System.DateTime> approveTime { get; set; }
        public string isactive { get; set; }
        public Nullable<System.DateTime> jobCardGenerationTime { get; set; }
        public string jobCardNumber { get; set; }
        public string session { get; set; }
        public string files { get; set; }
        public string remarks { get; set; }
        public string type { get; set; }
        public string jobCard_status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public byte[] OrderBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_jobcard_jobcardmember> tbl_jobcard_jobcardmember { get; set; }
    }
}
